// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSLogger")>]
[<assembly: AssemblyProductAttribute("FSLogger")>]
[<assembly: AssemblyDescriptionAttribute("F#ing simple logger for F#.")>]
[<assembly: AssemblyVersionAttribute("2.1")>]
[<assembly: AssemblyFileVersionAttribute("2.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSLogger"
    let [<Literal>] AssemblyProduct = "FSLogger"
    let [<Literal>] AssemblyDescription = "F#ing simple logger for F#."
    let [<Literal>] AssemblyVersion = "2.1"
    let [<Literal>] AssemblyFileVersion = "2.1"
